#!/bin/bash
#Menu
clear
echo -e ""
echo -e "============================= \e[1;33;44m MENU \e[0m ============================="
echo -e ""
echo -e "* menu         : List of Main Commands"
echo -e ""
echo -e "============================= \e[1;33;44m VMESS \e[0m ==========================="
echo -e ""
echo -e "* addws        : Create account vmess"
echo -e "* cekws        : Check user login vmess"
echo -e "* delws        : Delete account vmess"
echo -e "* renewws      : Update account vmess"
echo -e "* certv2ray    : Update certificate vmess"
echo -e ""
echo -e "============================= \e[1;33;44m VLESS \e[0m ==========================="
echo -e ""
echo -e "* addvless     : Create account vless"
echo -e "* cekvless     : Check user login vless"
echo -e "* delvless     : Delete account vless"
echo -e "* renewvless   : Update account vless"
echo -e ""
echo -e "============================= \e[1;33;44m SYSTEM \e[0m =========================="
echo -e ""
echo -e "* addhost      : Create host"
echo -e "* reboot       : Reboot VPS"
echo -e "* speedtest    : Speedtest VPS"
echo -e "* about        : Script auto install v2ray Info"
echo -e ""
echo -e "==============================================================="
echo -e " Modified by \e[1;33;44m Yolo \e[0m"
echo -e ""
